<script>
    import Title from './Title';
    import Section from './Section';
</script>

<div>
    <Section>
        Blazing fast UUID generator app. Optimized for fast loading and serving UUID.
        Will not reload the whole page to create a new id. Everything will happen in the browser.
    </Section>
    <Section>
        <Title>What is UUID</Title>
        A universally unique identifier (UUID) is a 128-bit number used to identify information in computer systems.
        <br />
        Source: 
        <a
            class="text-blue-500 underline"
            href="https://en.wikipedia.org/wiki/Universally_unique_identifier"
        >
            [wiki] Universally unique identifier
        </a>
    </Section>
    <Section>
        <Title>Disclamer</Title>
        The UUIDs generated by this site are provided AS-IS.
        There is no warranty of any kind.
        Moreover, the UUIDs generated by this site are not unique.
        You are responsible for using the UUIDs and assume any risk inherent to using them.
        You are not permitted to use the UUIDs generated by this site if you do not agree to these terms.
    </Section>
</div>