<script>
    import Title from './Title';
    import Section from './Section';
    import Link from './Link';
</script>

<div>
    <Section>
        The Blazing fast UUID generator app is optimized for fast loading and serving UUIDs.
        Unlike other UUID generators, it does not need to reload the entire page to create a new ID.
        All generation is done in the browser for the quickest and most efficient experience.
    </Section>
    <Section>
        <Title>What is UUID</Title>
        A universally unique identifier (UUID) is a 128-bit number used to identify information in computer systems.
        <br />
        Source:
        <Link href="https://en.wikipedia.org/wiki/Universally_unique_identifier">
            [wiki] Universally unique identifier
        </Link>
    </Section>
    <Section>
        <Title>Disclaimer</Title>
        The UUIDs generated by this site are provided AS-IS.
        There is no warranty of any kind.
        Moreover, the UUIDs generated by this site are not unique.
        You are responsible for using the UUIDs and assume any risk inherent to using them.
        You are not permitted to use the UUIDs generated by this site if you do not agree to these terms.
    </Section>
    <Section>
        <Link href="https://github.com/artemdemo/uuid-generator">
            Source code
        </Link>
    </Section>
</div>
