<script>
    import 'tailwindcss/dist/base.min.css';
    // import 'tailwindcss/dist/components.min.css';
    import 'tailwindcss/dist/utilities.min.css';

    import Button from './components/Button';
    import uuid from 'uuid/v4';

    let uuidResult = uuid();

    // Copies a string to the clipboard. Must be called from within an 
    // event handler such as click. May return false if it failed, but
    // this is not always possible. Browser support for Chrome 43+, 
    // Firefox 42+, Safari 10+, Edge and IE 10+.
    // IE: The clipboard feature may be disabled by an administrator. By
    // default a prompt is shown the first time the clipboard is 
    // used (per session).
    // @source https://stackoverflow.com/a/33928558
    function copyToClipboard(text) {
        if (window.clipboardData && window.clipboardData.setData) {
            // IE specific code path to prevent textarea being shown while dialog is visible.
            return clipboardData.setData("Text", text); 

        } else if (document.queryCommandSupported && document.queryCommandSupported("copy")) {
            var textarea = document.createElement("textarea");
            textarea.textContent = text;
            textarea.style.position = "fixed";  // Prevent scrolling to bottom of page in MS Edge.
            document.body.appendChild(textarea);
            textarea.select();
            try {
                return document.execCommand("copy");  // Security exception may be thrown by some browsers.
            } catch (ex) {
                console.warn("Copy to clipboard failed.", ex);
                return false;
            } finally {
                document.body.removeChild(textarea);
            }
        }
    }
</script>

<style></style>

<div class="container mx-auto px-4">
    <div class="max-w-xl mx-auto my-4">
        <div class="font-sans text-lg text-gray-800 my-4 text-xl">
            {uuidResult}
        </div>
        <Button
            secondary={true}
            onClick={() => {
                uuidResult = uuid();
            }}
        >
            Generate
        </Button>
        <Button
            secondary={true}
            onClick={() => {
                copyToClipboard(uuidResult);
            }}
        >
            Copy
        </Button>
        <Button
            onClick={() => {
                uuidResult = uuid();
                copyToClipboard(uuidResult);
            }}
        >
            Generate & Copy
        </Button>
    </div>
    <div class="max-w-xl mx-auto my-4 text-gray-800">
        Blazing fast UUID generator app. Optimized for fast loading and serving UUID.
        Will not reload the whole page to create a new id. Everything will happen in the browser.
    </div>
    <div class="max-w-xl mx-auto my-4 text-gray-800">
        <div class="font-bold my-4">What is UUID</div>
        A universally unique identifier (UUID) is a 128-bit number used to identify information in computer systems.
        <br />
        Source: 
        <a
            class="text-blue-500 underline"
            href="https://en.wikipedia.org/wiki/Universally_unique_identifier"
        >
            [wiki] Universally unique identifier
        </a>
    </div>
    <div class="max-w-xl mx-auto my-4 text-gray-800">
        <div class="font-bold my-4">Disclamer</div>
        The UUIDs generated by this site are provided AS-IS.
        There is no warranty of any kind.
        Moreover, the UUIDs generated by this site are not unique.
        You are responsible for using the UUIDs and assume any risk inherent to using them.
        You are not permitted to use the UUIDs generated by this site if you do not agree to these terms.
    </div>
</div>